### ISSUE TITLE
WriteXml/ReadXml method were removed from the TableContinuationToken class

### ISSUE THREAD

**Issue by VladimirKhvostov** [Azure/azure-cosmos-table-dotnet#22]
Microsoft.Azure.Cosmos**DB**.Table.TableContinuationToken class has WriteXml and ReadXml methods. Unfortunately, these methods do not exist in Microsoft.Azure.Cosmos.Table.TableContinuationToken, which makes upgrading from Microsoft.Azure.CosmosDB.Table to Microsoft.Azure.Cosmos.Table much more difficult.

**Comment by PaulCheng** [comment]
It was by design. Even in the deprecating CosmosDB Table 2.1.2, the read/writeXml methods were only compiled for windows desktop version. The new Cosmos Table sdk 1.0.x is a cross-platform .net standard lib, hence those methods were absent/removed.
The continuation token Properties have public setters, so read/write xml didn't have too much value.
